/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_05aa3c8a (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vbjueuhgcyfberivihiv/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables");
  }
  
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_05aa3c8a").upsert({
      key,
      value
    });
    if (error) {
      console.error(`❌ KV Set Error for key "${key}":`, error.message);
      throw new Error(`Failed to set key "${key}": ${error.message}`);
    }
  } catch (error) {
    console.error(`❌ KV Set Exception for key "${key}":`, error);
    throw error;
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_05aa3c8a").select("value").eq("key", key).maybeSingle();
    if (error) {
      console.error(`❌ KV Get Error for key "${key}":`, error.message);
      throw new Error(`Failed to get key "${key}": ${error.message}`);
    }
    return data?.value;
  } catch (error) {
    console.error(`❌ KV Get Exception for key "${key}":`, error);
    throw error;
  }
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_05aa3c8a").delete().eq("key", key);
    if (error) {
      console.error(`❌ KV Delete Error for key "${key}":`, error.message);
      throw new Error(`Failed to delete key "${key}": ${error.message}`);
    }
  } catch (error) {
    console.error(`❌ KV Delete Exception for key "${key}":`, error);
    throw error;
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_05aa3c8a").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
    if (error) {
      console.error(`❌ KV MSet Error for ${keys.length} keys:`, error.message);
      throw new Error(`Failed to set multiple keys: ${error.message}`);
    }
  } catch (error) {
    console.error(`❌ KV MSet Exception for ${keys.length} keys:`, error);
    throw error;
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_05aa3c8a").select("value").in("key", keys);
    if (error) {
      console.error(`❌ KV MGet Error for ${keys.length} keys:`, error.message);
      throw new Error(`Failed to get multiple keys: ${error.message}`);
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error) {
    console.error(`❌ KV MGet Exception for ${keys.length} keys:`, error);
    throw error;
  }
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  try {
    const supabase = client();
    const { error } = await supabase.from("kv_store_05aa3c8a").delete().in("key", keys);
    if (error) {
      console.error(`❌ KV MDel Error for ${keys.length} keys:`, error.message);
      throw new Error(`Failed to delete multiple keys: ${error.message}`);
    }
  } catch (error) {
    console.error(`❌ KV MDel Exception for ${keys.length} keys:`, error);
    throw error;
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  try {
    const supabase = client();
    const { data, error } = await supabase.from("kv_store_05aa3c8a").select("key, value").like("key", prefix + "%");
    if (error) {
      console.error(`❌ KV GetByPrefix Error for prefix "${prefix}":`, error.message);
      throw new Error(`Failed to get keys by prefix "${prefix}": ${error.message}`);
    }
    return data?.map((d) => d.value) ?? [];
  } catch (error) {
    console.error(`❌ KV GetByPrefix Exception for prefix "${prefix}":`, error);
    throw error;
  }
};

// Search for key-value pairs by prefix, returning both keys and values.
// Returns array of objects with both key and value: [{key: "...", value: {...}}]
export const getByPrefixWithKeys = async (prefix: string): Promise<Array<{key: string, value: any}>> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_05aa3c8a").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};